// DiningVenueKeys.swift — GENERATED. Do not edit by hand.
//
// Source of truth: Parkio-Website-Live/lib/diningVenueKeys.ts
// Regenerate with:
//   npm run dining:venuekeys:swift -- --output <iOS>/Parkio/Models/DiningVenueKeys.swift \
//                                      --sidecar <iOS>/Tools/VenueKeys/DiningVenueKeys.json
//
// sourceSha256: d5713912571b9814038e8c85acee46fae5dfd0e851f0e58b9f0018be02a35f12
// entries: 193
//
// venueKey is the Website-owned immutable identity a Community Rating is filed
// against. It is NOT a slug, NOT a stableID and NOT a display name, and it is
// never derived from a name at runtime — the mapping below is exhaustive and
// explicit, so an unmapped venue is simply not rateable rather than guessed at.
//
// The dictionary is keyed by the iOS stableID, "{Park.rawValue}|{land}|{name}",
// which is the same string the Website registry already uses as its key.

import Foundation

enum DiningVenueKeys {

    /// stableID → venueKey, for every venue the ratings backend accepts today.
    static let byStableID: [String: String] = [
        "Animal Kingdom|Africa|Dawa Bar": "ak-dawa-bar",
        "Animal Kingdom|Africa|Harambe Fruit Market": "ak-harambe-fruit-market",
        "Animal Kingdom|Africa|Harambe Market": "ak-harambe-market",
        "Animal Kingdom|Africa|Kusafiri Coffee Shop & Bakery": "ak-kusafiri",
        "Animal Kingdom|Africa|Mahindi": "ak-mahindi",
        "Animal Kingdom|Africa|Tamu Tamu Refreshments": "ak-tamu-tamu",
        "Animal Kingdom|Africa|Tusker House Restaurant": "ak-tusker-house",
        "Animal Kingdom|Asia|Anandapur Ice Cream Truck": "ak-anandapur-ice-cream-truck",
        "Animal Kingdom|Asia|Caravan Road": "ak-caravan-road",
        "Animal Kingdom|Asia|Drinkwallah": "ak-drinkwallah",
        "Animal Kingdom|Asia|Thirsty River Bar & Trek Snacks": "ak-thirsty-river",
        "Animal Kingdom|Asia|Warung Outpost": "ak-warung-outpost",
        "Animal Kingdom|Asia|Yak & Yeti Local Food Cafes": "ak-yak-and-yeti-local-food-cafes",
        "Animal Kingdom|Asia|Yak & Yeti Quality Beverages": "ak-yak-and-yeti-quality-beverages",
        "Animal Kingdom|Asia|Yak & Yeti Restaurant": "ak-yak-and-yeti-restaurant",
        "Animal Kingdom|Discovery Island|Creature Comforts": "ak-creature-comforts",
        "Animal Kingdom|Discovery Island|Eight Spoon Café": "ak-eight-spoon-cafe",
        "Animal Kingdom|Discovery Island|Flame Tree Barbecue": "ak-flame-tree-barbecue",
        "Animal Kingdom|Discovery Island|Isle of Java": "ak-isle-of-java",
        "Animal Kingdom|Discovery Island|Nomad Lounge & Cocktail Bar": "ak-nomad-lounge",
        "Animal Kingdom|Discovery Island|Pizzafari": "ak-pizzafari",
        "Animal Kingdom|Discovery Island|Terra Treats and Snack Shop": "ak-terra-treats",
        "Animal Kingdom|Discovery Island|The Smiling Crocodile": "ak-smiling-crocodile",
        "Animal Kingdom|Discovery Island|Tiffins Restaurant": "ak-tiffins",
        "Animal Kingdom|Main Entrance|Rainforest Cafe at Disney's Animal Kingdom": "ak-rainforest-cafe",
        "Animal Kingdom|Pandora|Pongu Pongu": "ak-pongu-pongu",
        "Animal Kingdom|Pandora|Satu'li Canteen": "ak-satuli-canteen",
        "Disney California Adventure|Avengers Campus|Pym Tasting Lab": "dca-pym-tasting-lab",
        "Disney California Adventure|Avengers Campus|Pym Test Kitchen": "dca-pym-test-kitchen",
        "Disney California Adventure|Avengers Campus|Shawarma Palace": "dca-shawarma-palace",
        "Disney California Adventure|Avengers Campus|Terran Treats": "dca-terran-treats",
        "Disney California Adventure|Buena Vista Street|Carthay Circle Lounge": "dca-carthay-circle-lounge",
        "Disney California Adventure|Buena Vista Street|Carthay Circle Restaurant": "dca-carthay-circle-restaurant",
        "Disney California Adventure|Buena Vista Street|Clarabelle's Hand-Scooped Ice Cream": "dca-clarabelles-ice-cream",
        "Disney California Adventure|Buena Vista Street|Fiddler, Fifer & Practical Cafe": "dca-fiddler-fifer-and-practical-cafe",
        "Disney California Adventure|Cars Land|Cozy Cone Motel": "dca-cozy-cone-motel",
        "Disney California Adventure|Cars Land|Fillmore's Taste-In": "dca-fillmores-taste-in",
        "Disney California Adventure|Cars Land|Flo's V8 Café": "dca-flos-v8-cafe",
        "Disney California Adventure|Grizzly Peak|Smokejumpers Grill": "dca-smokejumpers-grill",
        "Disney California Adventure|Hollywood Land|Award Wieners": "dca-award-wieners",
        "Disney California Adventure|Hollywood Land|Fairfax Market": "dca-fairfax-market",
        "Disney California Adventure|Hollywood Land|Hollywood Lounge": "dca-hollywood-lounge",
        "Disney California Adventure|Hollywood Land|Schmoozies!": "dca-schmoozies",
        "Disney California Adventure|Hollywood Land|Studio Catering Co.": "dca-studio-catering-co",
        "Disney California Adventure|Paradise Gardens Park|Bayside Brews": "dca-bayside-brews",
        "Disney California Adventure|Paradise Gardens Park|Boardwalk Pizza & Pasta": "dca-boardwalk-pizza-and-pasta",
        "Disney California Adventure|Paradise Gardens Park|Corn Dog Castle": "dca-corn-dog-castle",
        "Disney California Adventure|Paradise Gardens Park|Paradise Garden Grill": "dca-paradise-garden-grill",
        "Disney California Adventure|Performance Corridor|Magic Key Terrace - Magic Key Holder Dining": "dca-magic-key-terrace",
        "Disney California Adventure|Performance Corridor|Mendocino Terrace": "dca-mendocino-terrace",
        "Disney California Adventure|Performance Corridor|Sonoma Terrace": "dca-sonoma-terrace",
        "Disney California Adventure|Performance Corridor|Wine Country Trattoria": "dca-wine-country-trattoria",
        "Disney California Adventure|Pixar Pier|Adorable Snowman Frosted Treats": "dca-adorable-snowman",
        "Disney California Adventure|Pixar Pier|Angry Dogs": "dca-angry-dogs",
        "Disney California Adventure|Pixar Pier|Jack-Jack Cookie Num Nums": "dca-jack-jack-cookie-num-nums",
        "Disney California Adventure|Pixar Pier|Lamplight Lounge": "dca-lamplight-lounge",
        "Disney California Adventure|Pixar Pier|Poultry Palace": "dca-poultry-palace",
        "Disney California Adventure|Pixar Pier|Señor Buzz Churros": "dca-senor-buzz-churros",
        "Disney California Adventure|San Fransokyo Square|Aunt Cass Café": "dca-aunt-cass-cafe",
        "Disney California Adventure|San Fransokyo Square|Cappuccino Cart": "dca-cappuccino-cart",
        "Disney California Adventure|San Fransokyo Square|Cocina Cucamonga Mexican Grill": "dca-cocina-cucamonga",
        "Disney California Adventure|San Fransokyo Square|Ghirardelli® Soda Fountain and Chocolate Shop": "dca-ghirardelli",
        "Disney California Adventure|San Fransokyo Square|Lucky Fortune Cookery": "dca-lucky-fortune-cookery",
        "Disney California Adventure|San Fransokyo Square|Port of San Fransokyo Cervecería": "dca-port-of-san-fransokyo",
        "Disney California Adventure|San Fransokyo Square|Rita's Turbine Blenders": "dca-ritas-turbine-blenders",
        "Disneyland|Adventureland|Bengal Barbecue": "dl-bengal-barbecue",
        "Disneyland|Adventureland|South Seas Traders": "dl-south-seas-traders",
        "Disneyland|Adventureland|The Tropical Hideaway": "dl-tropical-hideaway",
        "Disneyland|Adventureland|Tiki Juice Bar": "dl-tiki-juice-bar",
        "Disneyland|Bayou Country|Hungry Bear Barbecue Jamboree": "dl-hungry-bear",
        "Disneyland|Fantasyland|Edelweiss Snacks": "dl-edelweiss-snacks",
        "Disneyland|Fantasyland|Maurice's Treats": "dl-maurices-treats",
        "Disneyland|Fantasyland|Red Rose Taverne": "dl-red-rose-taverne",
        "Disneyland|Fantasyland|Troubadour Tavern": "dl-troubadour-tavern",
        "Disneyland|Frontierland|Rancho del Zocalo Restaurante": "dl-rancho-del-zocalo",
        "Disneyland|Frontierland|River Belle Terrace": "dl-river-belle-terrace",
        "Disneyland|Frontierland|Stage Door Café": "dl-stage-door-cafe",
        "Disneyland|Frontierland|The Golden Horseshoe": "dl-golden-horseshoe",
        "Disneyland|Main Street, U.S.A.|Carnation Café": "dl-carnation-cafe",
        "Disneyland|Main Street, U.S.A.|Gibson Girl Ice Cream Parlor": "dl-gibson-girl",
        "Disneyland|Main Street, U.S.A.|Jolly Holiday Bakery Cafe": "dl-jolly-holiday",
        "Disneyland|Main Street, U.S.A.|Little Red Wagon": "dl-little-red-wagon",
        "Disneyland|Main Street, U.S.A.|Market House": "dl-market-house",
        "Disneyland|Main Street, U.S.A.|Plaza Inn": "dl-plaza-inn",
        "Disneyland|Main Street, U.S.A.|Refreshment Corner": "dl-refreshment-corner",
        "Disneyland|Mickey's Toontown|Café Daisy": "dl-cafe-daisy",
        "Disneyland|Mickey's Toontown|Good Boy! Grocers": "dl-good-boy-grocers",
        "Disneyland|New Orleans Square|Blue Bayou Restaurant": "dl-blue-bayou",
        "Disneyland|New Orleans Square|Cafe Orleans": "dl-cafe-orleans",
        "Disneyland|New Orleans Square|Harbour Galley": "dl-harbour-galley",
        "Disneyland|New Orleans Square|Mint Julep Bar": "dl-mint-julep-bar",
        "Disneyland|New Orleans Square|Royal Street Veranda": "dl-royal-street-veranda",
        "Disneyland|New Orleans Square|Tiana's Palace": "dl-tianas-palace",
        "Disneyland|Star Wars: Galaxy's Edge|Docking Bay 7 Food and Cargo": "dl-docking-bay-7",
        "Disneyland|Star Wars: Galaxy's Edge|Kat Saka's Kettle": "dl-kat-sakas-kettle",
        "Disneyland|Star Wars: Galaxy's Edge|Milk Stand": "dl-milk-stand",
        "Disneyland|Star Wars: Galaxy's Edge|Oga's Cantina at the Disneyland Resort": "dl-ogas-cantina",
        "Disneyland|Star Wars: Galaxy's Edge|Ronto Roasters": "dl-ronto-roasters",
        "Disneyland|Tomorrowland|Alien Pizza Planet": "dl-alien-pizza-planet",
        "Disneyland|Tomorrowland|Galactic Grill": "dl-galactic-grill",
        "EPCOT|World Celebration|Connections Eatery": "ep-connections-eatery",
        "EPCOT|World Celebration|GEO-82": "ep-geo-82",
        "EPCOT|World Celebration|GRAB-N-GOOF": "ep-grab-n-goof",
        "EPCOT|World Discovery|Space 220 Lounge": "ep-space-220-lounge",
        "EPCOT|World Discovery|Space 220 Restaurant": "ep-space-220",
        "EPCOT|World Nature|Garden Grill Restaurant": "ep-garden-grill",
        "EPCOT|World Nature|Sunshine Seasons": "ep-sunshine-seasons",
        "EPCOT|World Showcase|Akershus Royal Banquet Hall": "ep-akershus",
        "EPCOT|World Showcase|Biergarten Restaurant": "ep-biergarten",
        "EPCOT|World Showcase|Block & Hans": "ep-block-and-hans",
        "EPCOT|World Showcase|Chefs de France": "ep-chefs-de-france",
        "EPCOT|World Showcase|Choza de Margarita": "ep-choza-de-margarita",
        "EPCOT|World Showcase|Fife & Drum Tavern": "ep-fife-and-drum",
        "EPCOT|World Showcase|Karamell-Küche": "ep-karamell-kuche",
        "EPCOT|World Showcase|Katsura Grill": "ep-katsura-grill",
        "EPCOT|World Showcase|L'Artisan des Glaces": "ep-lartisan-des-glaces",
        "EPCOT|World Showcase|La Cantina de San Angel": "ep-la-cantina",
        "EPCOT|World Showcase|La Cava del Tequila": "ep-la-cava",
        "EPCOT|World Showcase|La Crêperie de Paris": "ep-la-creperie",
        "EPCOT|World Showcase|La Hacienda de San Angel": "ep-la-hacienda",
        "EPCOT|World Showcase|La Poutinerie": "ep-la-poutinerie",
        "EPCOT|World Showcase|Le Cellier Steakhouse": "ep-le-cellier",
        "EPCOT|World Showcase|Les Halles Boulangerie-Patisserie": "ep-les-halles",
        "EPCOT|World Showcase|Les Vins des Chefs de France": "ep-les-vins-de-france",
        "EPCOT|World Showcase|Monsieur Paul": "ep-monsieur-paul",
        "EPCOT|World Showcase|Nine Dragons Restaurant": "ep-nine-dragons",
        "EPCOT|World Showcase|Refreshment Outpost": "ep-refreshment-outpost",
        "EPCOT|World Showcase|Regal Eagle Smokehouse": "ep-regal-eagle",
        "EPCOT|World Showcase|Rose & Crown Dining Room": "ep-rose-and-crown",
        "EPCOT|World Showcase|Rose & Crown Pub": "ep-rose-and-crown-pub",
        "EPCOT|World Showcase|San Angel Inn Restaurante": "ep-san-angel-inn",
        "EPCOT|World Showcase|Shiki-Sai: Sushi Izakaya": "ep-shiki-sai",
        "EPCOT|World Showcase|Sommerfest": "ep-sommerfest",
        "EPCOT|World Showcase|Spice Road Table": "ep-spice-road-table",
        "EPCOT|World Showcase|Takumi-Tei": "ep-takumi-tei",
        "EPCOT|World Showcase|Tangierine Café": "ep-tangierine-cafe",
        "EPCOT|World Showcase|Teppan Edo": "ep-teppan-edo",
        "EPCOT|World Showcase|Tutto Gusto Wine Cellar": "ep-tutto-gusto",
        "EPCOT|World Showcase|Tutto Italia Ristorante": "ep-tutto-italia",
        "EPCOT|World Showcase|UK Beer Cart": "ep-uk-beer-cart",
        "EPCOT|World Showcase|Via Napoli Ristorante e Pizzeria": "ep-via-napoli",
        "EPCOT|World Showcase|Yorkshire County Fish Shop": "ep-yorkshire-fish-shop",
        "Hollywood Studios|Commissary Lane|ABC Commissary": "hs-abc-commissary",
        "Hollywood Studios|Commissary Lane|Sci-Fi Dine-In Theater Restaurant": "hs-sci-fi-dine-in",
        "Hollywood Studios|Echo Lake|50's Prime Time Cafe": "hs-50s-prime-time",
        "Hollywood Studios|Echo Lake|Backlot Express": "hs-backlot-express",
        "Hollywood Studios|Echo Lake|Dockside Diner": "hs-dockside-diner",
        "Hollywood Studios|Echo Lake|Hollywood & Vine": "hs-hollywood-and-vine",
        "Hollywood Studios|Echo Lake|Tune-In Lounge": "hs-tune-in-lounge",
        "Hollywood Studios|Grand Avenue|BaseLine Tap House": "hs-baseline-tap-house",
        "Hollywood Studios|Hollywood Boulevard|The Hollywood Brown Derby": "hs-brown-derby",
        "Hollywood Studios|Hollywood Boulevard|The Hollywood Brown Derby Lounge": "hs-brown-derby-lounge",
        "Hollywood Studios|Star Wars: Galaxy's Edge|Docking Bay 7 Food and Cargo": "hs-docking-bay-7",
        "Hollywood Studios|Star Wars: Galaxy's Edge|Kat Saka's Kettle": "hs-kat-sakas-kettle",
        "Hollywood Studios|Star Wars: Galaxy's Edge|Milk Stand": "hs-milk-stand",
        "Hollywood Studios|Star Wars: Galaxy's Edge|Oga's Cantina": "hs-ogas-cantina",
        "Hollywood Studios|Star Wars: Galaxy's Edge|Ronto Roasters": "hs-ronto-roasters",
        "Hollywood Studios|Sunset Boulevard|Catalina Eddie's": "hs-catalina-eddies",
        "Hollywood Studios|Sunset Boulevard|Fairfax Fare": "hs-fairfax-fare",
        "Hollywood Studios|Sunset Boulevard|Rosie's All-American Cafe": "hs-rosies",
        "Hollywood Studios|Toy Story Land|Roundup Rodeo BBQ": "hs-roundup-rodeo",
        "Hollywood Studios|Toy Story Land|Woody's Lunch Box": "hs-woodys-lunch-box",
        "Magic Kingdom|Adventureland|Aloha Isle": "mk-aloha-isle",
        "Magic Kingdom|Adventureland|Jungle Navigation Co. LTD Skipper Canteen": "mk-skipper-canteen",
        "Magic Kingdom|Adventureland|Spring Roll Snack Cart": "mk-spring-roll-cart",
        "Magic Kingdom|Adventureland|Sunshine Tree Terrace": "mk-sunshine-tree-terrace",
        "Magic Kingdom|Adventureland|The Beak and Barrel": "mk-beak-and-barrel",
        "Magic Kingdom|Fantasyland|Be Our Guest Restaurant": "mk-be-our-guest",
        "Magic Kingdom|Fantasyland|Cheshire Café": "mk-cheshire-cafe",
        "Magic Kingdom|Fantasyland|Cinderella's Royal Table": "mk-cinderellas-royal-table",
        "Magic Kingdom|Fantasyland|Gaston's Tavern": "mk-gastons-tavern",
        "Magic Kingdom|Fantasyland|Pinocchio Village Haus": "mk-pinocchio-village-haus",
        "Magic Kingdom|Fantasyland|Prince Eric's Village Market": "mk-prince-erics-village-market",
        "Magic Kingdom|Fantasyland|Storybook Treats": "mk-storybook-treats",
        "Magic Kingdom|Fantasyland|The Friar's Nook": "mk-friars-nook",
        "Magic Kingdom|Frontierland|Golden Oak Outpost": "mk-golden-oak-outpost",
        "Magic Kingdom|Frontierland|Pecos Bill Tall Tale Inn and Cafe": "mk-pecos-bill",
        "Magic Kingdom|Liberty Square|Liberty Tree Tavern": "mk-liberty-tree-tavern",
        "Magic Kingdom|Liberty Square|Sleepy Hollow": "mk-sleepy-hollow",
        "Magic Kingdom|Liberty Square|The Diamond Horseshoe": "mk-diamond-horseshoe",
        "Magic Kingdom|Main Street, U.S.A.|Casey's Corner": "mk-caseys-corner",
        "Magic Kingdom|Main Street, U.S.A.|Main Street Bakery": "mk-main-street-bakery",
        "Magic Kingdom|Main Street, U.S.A.|Plaza Ice Cream Parlor": "mk-plaza-ice-cream-parlor",
        "Magic Kingdom|Main Street, U.S.A.|The Crystal Palace": "mk-crystal-palace",
        "Magic Kingdom|Main Street, U.S.A.|The Plaza Restaurant": "mk-plaza-restaurant",
        "Magic Kingdom|Main Street, U.S.A.|Tony's Town Square Restaurant": "mk-tonys-town-square",
        "Magic Kingdom|Tomorrowland|AstroFizz Hosted by Coca-Cola": "mk-astrofizz",
        "Magic Kingdom|Tomorrowland|Auntie Gravity's Galactic Goodies": "mk-auntie-gravitys",
        "Magic Kingdom|Tomorrowland|Cosmic Ray's Starlight Café": "mk-cosmic-rays",
        "Magic Kingdom|Tomorrowland|Energy Bytes": "mk-energy-bytes",
        "Magic Kingdom|Tomorrowland|Fireworks Dessert Parties at Tomorrowland Terrace Restaurant": "mk-tomorrowland-terrace-dessert-party",
        "Magic Kingdom|Tomorrowland|Joffrey's Coffee & Tea Company": "mk-joffreys",
        "Magic Kingdom|Tomorrowland|The Lunching Pad": "mk-lunching-pad",
    ]

    /// Number of venues the backend currently accepts. Guards against a
    /// silent partial regeneration.
    static let expectedCount = 193

    /// The venueKey for a venue, or nil when it is not rateable yet.
    static func venueKey(forStableID stableID: String) -> String? {
        byStableID[stableID]
    }

    /// Whether this venue can currently be rated.
    static func isRateable(stableID: String) -> Bool {
        byStableID[stableID] != nil
    }
}
